version: '3.3'

services:  
  ws-sender-database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined