version: '3.3'

services:  
  ws-sender-database:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:3306
    security_opt:
      - seccomp:unconfined